/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    doctors: Doctor;
    'service-categories': ServiceCategory;
    services: Service;
    prices: Price;
    reviews: Review;
    cases: Case;
    faqs: Faq;
    'article-categories': ArticleCategory;
    articles: Article;
    technologies: Technology;
    'clinic-advantages': ClinicAdvantage;
    appointments: Appointment;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    'service-categories': ServiceCategoriesSelect<false> | ServiceCategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    prices: PricesSelect<false> | PricesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'article-categories': ArticleCategoriesSelect<false> | ArticleCategoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    'clinic-advantages': ClinicAdvantagesSelect<false> | ClinicAdvantagesSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'homepage-settings': HomepageSetting;
    'header-settings': HeaderSetting;
    'footer-settings': FooterSetting;
    'seo-settings': SeoSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'homepage-settings': HomepageSettingsSelect<false> | HomepageSettingsSelect<true>;
    'header-settings': HeaderSettingsSelect<false> | HeaderSettingsSelect<true>;
    'footer-settings': FooterSettingsSelect<false> | FooterSettingsSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Администраторы и редакторы сайта
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Изображения и файлы клиники
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Описание изображения для доступности и SEO
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Профили врачей клиники
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: string;
  name: string;
  /**
   * URL-идентификатор. Генерируется автоматически из названия.
   */
  slug: string;
  photo?: (string | null) | Media;
  position: string;
  specialization: string;
  /**
   * Количество лет опыта работы
   */
  experienceYears?: number | null;
  education?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  certificates?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Краткое описание философии и подхода врача
   */
  approach?: string | null;
  /**
   * Услуги, которые оказывает врач
   */
  services?: (string | Service)[] | null;
  categories?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Метаданные для поисковых систем и социальных сетей
   */
  seo?: {
    /**
     * Заголовок страницы в поисковой выдаче (рекомендуется до 60 символов)
     */
    metaTitle?: string | null;
    /**
     * Описание для сниппета в поиске (рекомендуется до 160 символов)
     */
    metaDescription?: string | null;
    /**
     * Изображение для превью в соцсетях (рекомендуется 1200×630)
     */
    ogImage?: (string | null) | Media;
    /**
     * Канонический URL страницы (если отличается от текущего)
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Стоматологические услуги клиники
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  /**
   * URL-идентификатор. Генерируется автоматически из названия.
   */
  slug: string;
  category: string | ServiceCategory;
  /**
   * Короткий текст для карточек и списков
   */
  shortDescription: string;
  description: string;
  image?: (string | null) | Media;
  /**
   * Минимальная стоимость услуги в рублях
   */
  priceFrom?: number | null;
  /**
   * Например: «точная стоимость после осмотра»
   */
  priceNote?: string | null;
  whenNeeded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  process?: string | null;
  stages?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  technologies?: (string | Technology)[] | null;
  doctors?: (string | Doctor)[] | null;
  faq?: (string | Faq)[] | null;
  relatedServices?: (string | Service)[] | null;
  /**
   * Метаданные для поисковых систем и социальных сетей
   */
  seo?: {
    /**
     * Заголовок страницы в поисковой выдаче (рекомендуется до 60 символов)
     */
    metaTitle?: string | null;
    /**
     * Описание для сниппета в поиске (рекомендуется до 160 символов)
     */
    metaDescription?: string | null;
    /**
     * Изображение для превью в соцсетях (рекомендуется 1200×630)
     */
    ogImage?: (string | null) | Media;
    /**
     * Канонический URL страницы (если отличается от текущего)
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Группы стоматологических услуг
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories".
 */
export interface ServiceCategory {
  id: string;
  title: string;
  /**
   * URL-идентификатор. Генерируется автоматически из названия.
   */
  slug: string;
  description?: string | null;
  /**
   * Чем меньше число, тем выше в списке
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Оборудование и технологии клиники
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: string;
  title: string;
  /**
   * URL-идентификатор. Генерируется автоматически из названия.
   */
  slug: string;
  description: string;
  icon: 'scan' | 'microscope' | 'cadcam' | 'anesthesia' | 'sterilization' | 'diagnostics';
  /**
   * Опциональное фото оборудования
   */
  image?: (string | null) | Media;
  /**
   * Чем меньше число, тем выше в списке
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Часто задаваемые вопросы пациентов
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  question: string;
  answer: string;
  category: 'general' | 'treatment' | 'prices' | 'preparation';
  /**
   * Чем меньше число, тем выше в списке
   */
  order?: number | null;
  /**
   * Опциональная привязка к услуге
   */
  relatedService?: (string | null) | Service;
  updatedAt: string;
  createdAt: string;
}
/**
 * Прайс-лист услуг
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices".
 */
export interface Price {
  id: string;
  title: string;
  category: string | ServiceCategory;
  /**
   * Опциональная привязка к карточке услуги
   */
  service?: (string | null) | Service;
  priceFrom: number;
  /**
   * Валюта или единица измерения
   */
  unit?: string | null;
  /**
   * Чем меньше число, тем выше в списке
   */
  order?: number | null;
  /**
   * Показывать в выделенном блоке прайса
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Отзывы пациентов о клинике
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  name: string;
  text: string;
  /**
   * Оценка от 1 до 5
   */
  rating: number;
  date: string;
  service?: (string | null) | Service;
  doctor?: (string | null) | Doctor;
  /**
   * Опциональное фото пациента или кейса
   */
  photo?: (string | null) | Media;
  /**
   * Показывать на главной и в выделенных блоках
   */
  isFeatured?: boolean | null;
  /**
   * Пометить как демонстрационный / placeholder-контент
   */
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Примеры работ «до / после»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: string;
  title: string;
  /**
   * URL-идентификатор. Генерируется автоматически из названия.
   */
  slug: string;
  service: string | Service;
  doctor?: (string | null) | Doctor;
  description: string;
  beforeImage: string | Media;
  afterImage: string | Media;
  /**
   * Например: «2 визита» или «3 недели»
   */
  duration?: string | null;
  /**
   * Юридическая оговорка: результаты индивидуальны и т.п.
   */
  disclaimer?: string | null;
  /**
   * Метаданные для поисковых систем и социальных сетей
   */
  seo?: {
    /**
     * Заголовок страницы в поисковой выдаче (рекомендуется до 60 символов)
     */
    metaTitle?: string | null;
    /**
     * Описание для сниппета в поиске (рекомендуется до 160 символов)
     */
    metaDescription?: string | null;
    /**
     * Изображение для превью в соцсетях (рекомендуется 1200×630)
     */
    ogImage?: (string | null) | Media;
    /**
     * Канонический URL страницы (если отличается от текущего)
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Рубрики блога и полезных материалов
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories".
 */
export interface ArticleCategory {
  id: string;
  title: string;
  /**
   * URL-идентификатор. Генерируется автоматически из названия.
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Статьи блога и полезные материалы
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  /**
   * URL-идентификатор. Генерируется автоматически из названия.
   */
  slug: string;
  /**
   * Краткое описание для карточек и превью
   */
  excerpt: string;
  content: string;
  coverImage?: (string | null) | Media;
  /**
   * Имя автора статьи
   */
  author?: string | null;
  category: string | ArticleCategory;
  publishedAt?: string | null;
  /**
   * Метаданные для поисковых систем и социальных сетей
   */
  seo?: {
    /**
     * Заголовок страницы в поисковой выдаче (рекомендуется до 60 символов)
     */
    metaTitle?: string | null;
    /**
     * Описание для сниппета в поиске (рекомендуется до 160 символов)
     */
    metaDescription?: string | null;
    /**
     * Изображение для превью в соцсетях (рекомендуется 1200×630)
     */
    ogImage?: (string | null) | Media;
    /**
     * Канонический URL страницы (если отличается от текущего)
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Ключевые преимущества клиники для сайта
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-advantages".
 */
export interface ClinicAdvantage {
  id: string;
  title: string;
  description: string;
  icon: 'equipment' | 'digital' | 'sterile' | 'specialists' | 'pricing' | 'plan' | 'guarantee' | 'comfort';
  /**
   * Чем меньше число, тем выше в списке
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Заявки на запись с сайта. Публичное создание только через /api/appointments.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  name: string;
  phone: string;
  /**
   * Необязательный email для связи
   */
  email?: string | null;
  /**
   * Желаемая услуга (необязательно)
   */
  service?: (string | null) | Service;
  preferredDate?: string | null;
  comment?: string | null;
  status: 'new' | 'contacted' | 'confirmed' | 'completed' | 'cancelled';
  /**
   * Пациент дал согласие на обработку ПДн
   */
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Редактируемый контент: о клинике, политика, оферта и т.п.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL-идентификатор. Генерируется автоматически из названия.
   */
  slug: string;
  content: string;
  /**
   * Метаданные для поисковых систем и социальных сетей
   */
  seo?: {
    /**
     * Заголовок страницы в поисковой выдаче (рекомендуется до 60 символов)
     */
    metaTitle?: string | null;
    /**
     * Описание для сниппета в поиске (рекомендуется до 160 символов)
     */
    metaDescription?: string | null;
    /**
     * Изображение для превью в соцсетях (рекомендуется 1200×630)
     */
    ogImage?: (string | null) | Media;
    /**
     * Канонический URL страницы (если отличается от текущего)
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'doctors';
        value: string | Doctor;
      } | null)
    | ({
        relationTo: 'service-categories';
        value: string | ServiceCategory;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'prices';
        value: string | Price;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'cases';
        value: string | Case;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'article-categories';
        value: string | ArticleCategory;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'technologies';
        value: string | Technology;
      } | null)
    | ({
        relationTo: 'clinic-advantages';
        value: string | ClinicAdvantage;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  position?: T;
  specialization?: T;
  experienceYears?: T;
  education?:
    | T
    | {
        item?: T;
        id?: T;
      };
  certificates?:
    | T
    | {
        item?: T;
        id?: T;
      };
  approach?: T;
  services?: T;
  categories?:
    | T
    | {
        item?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories_select".
 */
export interface ServiceCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  shortDescription?: T;
  description?: T;
  image?: T;
  priceFrom?: T;
  priceNote?: T;
  whenNeeded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  process?: T;
  stages?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  technologies?: T;
  doctors?: T;
  faq?: T;
  relatedServices?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prices_select".
 */
export interface PricesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  service?: T;
  priceFrom?: T;
  unit?: T;
  order?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  text?: T;
  rating?: T;
  date?: T;
  service?: T;
  doctor?: T;
  photo?: T;
  isFeatured?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  service?: T;
  doctor?: T;
  description?: T;
  beforeImage?: T;
  afterImage?: T;
  duration?: T;
  disclaimer?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  relatedService?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories_select".
 */
export interface ArticleCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  author?: T;
  category?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  icon?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-advantages_select".
 */
export interface ClinicAdvantagesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  service?: T;
  preferredDate?: T;
  comment?: T;
  status?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Основные контактные данные и брендинг клиники
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  clinicName: string;
  phone: string;
  email: string;
  address: string;
  city: string;
  district?: string | null;
  workingHours?:
    | {
        /**
         * Например: Пн–Пт или Суббота
         */
        day: string;
        /**
         * Например: 9:00–21:00
         */
        hours: string;
        id?: string | null;
      }[]
    | null;
  social?: {
    telegram?: string | null;
    whatsapp?: string | null;
    vk?: string | null;
    youtube?: string | null;
  };
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  /**
   * Опциональный iframe/embed URL (Яндекс/Google). Без него карта не загружается.
   */
  mapEmbedUrl?: string | null;
  defaultSEO?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  ctaPrimaryText?: string | null;
  ctaSecondaryText?: string | null;
  /**
   * Демо-плейсхолдеры для блока доверия (можно заменить реальными данными)
   */
  trustStats?:
    | {
        /**
         * Демо-плейсхолдер: например «лет опыта»
         */
        label: string;
        /**
         * Демо-плейсхолдер: например «15+»
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Тексты, изображения и видимость блоков главной. Списки услуг/врачей/отзывов редактируются в соответствующих коллекциях.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings".
 */
export interface HomepageSetting {
  id: string;
  seo?: {
    /**
     * Если пусто — берётся title из SEO / настроек сайта
     */
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    /**
     * Можно использовать перенос строки
     */
    title?: string | null;
    subtitle?: string | null;
    primaryCtaLabel?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    image?: (string | null) | Media;
    imageAlt?: string | null;
    statsLabel?: string | null;
  };
  trustBar?: {
    enabled?: boolean | null;
    items?:
      | {
          icon: 'doctors' | 'equipment' | 'guarantee' | 'plan' | 'diagnostics' | 'comfort' | 'sterile' | 'digital';
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    limit?: number | null;
  };
  whyUs?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  doctors?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    limit?: number | null;
  };
  technology?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  cases?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    disclaimer?: string | null;
    limit?: number | null;
  };
  reviews?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    limit?: number | null;
  };
  about?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    blurb?: string | null;
    image?: (string | null) | Media;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  faq?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    limit?: number | null;
  };
  blog?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    limit?: number | null;
  };
  cta?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    benefits?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  contacts?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Настройки навигации и CTA в шапке
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-settings".
 */
export interface HeaderSetting {
  id: string;
  /**
   * Отображать телефон клиники в шапке
   */
  showPhone?: boolean | null;
  ctaText?: string | null;
  navLinks?:
    | {
        label: string;
        /**
         * Путь или URL, например /services
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Описание, колонки ссылок и копирайт в подвале
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings".
 */
export interface FooterSetting {
  id: string;
  /**
   * Краткий текст о клинике в подвале
   */
  description?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Например: © 2026 Название клиники
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Глобальные SEO-параметры сайта
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: string;
  siteName: string;
  defaultTitle: string;
  /**
   * Используйте %s для подстановки заголовка страницы
   */
  titleTemplate?: string | null;
  defaultDescription: string;
  /**
   * Если выключено — сайт будет с noindex
   */
  robotsIndex?: boolean | null;
  /**
   * Код верификации Google Search Console
   */
  googleSiteVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  clinicName?: T;
  phone?: T;
  email?: T;
  address?: T;
  city?: T;
  district?: T;
  workingHours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  social?:
    | T
    | {
        telegram?: T;
        whatsapp?: T;
        vk?: T;
        youtube?: T;
      };
  logo?: T;
  favicon?: T;
  mapEmbedUrl?: T;
  defaultSEO?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  ctaPrimaryText?: T;
  ctaSecondaryText?: T;
  trustStats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings_select".
 */
export interface HomepageSettingsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        image?: T;
        imageAlt?: T;
        statsLabel?: T;
      };
  trustBar?:
    | T
    | {
        enabled?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        limit?: T;
      };
  whyUs?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  doctors?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        limit?: T;
      };
  technology?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  cases?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        disclaimer?: T;
        limit?: T;
      };
  reviews?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        limit?: T;
      };
  about?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        blurb?: T;
        image?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  faq?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        limit?: T;
      };
  blog?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        limit?: T;
      };
  cta?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  contacts?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        description?: T;
        ctaLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-settings_select".
 */
export interface HeaderSettingsSelect<T extends boolean = true> {
  showPhone?: T;
  ctaText?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-settings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  description?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  siteName?: T;
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  robotsIndex?: T;
  googleSiteVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}